using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Security.Permissions;
using Pathfinding;
using Pathfinding.Collections;
using Pathfinding.Graphs.Navmesh;
using Pathfinding.RVO;
using Pathfinding.Util;
using Unity.Burst;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: InternalsVisibleTo("AstarPathfindingProjectEditor")]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Polygon.ContainsPoint_000002E3$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Polygon.ClosestPointOnTriangleByRef_000002E9$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Polygon.ClosestPointOnTriangleProjected_000002EC$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BinaryHeap.Add_000002FF$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BinaryHeap.Remove_00000302$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(HeuristicObjective.Calculate_000004C3$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Path.OpenCandidateConnectionBurst_00000500$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(TriangleMeshNode.InterpolateEdge_00000761$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(TriangleMeshNode.OpenSingleEdgeBurst_00000766$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(TriangleMeshNode.CalculateBestEdgePosition_00000767$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(NavmeshCutJobs.CalculateContour_000008B4$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Funnel.Calculate_00000954$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Funnel.FunnelState.PushStart_00000960$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Funnel.FunnelState.ConvertCornerIndicesToPathProjected_0000096A$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(PathTracer.ContainsAndProject_00000992$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(PathTracer.EstimateRemainingPath_000009A5$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(PathTracer.RemainingDistanceLowerBound_000009A9$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(ColliderMeshBuilder2D.GenerateMeshesFromShapes_00000A8B$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(RecastMeshGatherer.CalculateBounds_00000A98$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(RecastMeshGatherer.GenerateHeightmapChunk_00000AA9$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(TileHandler.ConvertVerticesAndSnapToTileBoundaries_00000AD4$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(TileHandler.CutTiles_00000AD5$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(HierarchicalBitset.Iterator.MoveNextBurst_00000D4C$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BBTree.Build_00000DDE$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BBTree.ProjectionParams.SquaredRectPointDistanceOnPlane_00000DE9$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BBTree.NearbyNodesIterator.MoveNext_00000DF0$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(MeshUtility.MakeTrianglesClockwise_00000EBC$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(RVOObstacleCache.TraceContours_00000F8F$BurstDirectCall))]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
