using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyVersion("4.0.10.0")]
[assembly: AssemblyTitle("System.Collections")]
[assembly: AssemblyDescription("System.Collections")]
[assembly: AssemblyDefaultAlias("System.Collections")]
[assembly: AssemblyCompany("Mono development team")]
[assembly: AssemblyProduct("Mono Common Language Infrastructure")]
[assembly: AssemblyCopyright("(c) Various Mono authors")]
[assembly: AssemblyInformationalVersion("4.0.0.0")]
[assembly: AssemblyFileVersion("4.0.0.0")]
// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[assembly: TypeForwardedTo(typeof(BitArray))]
[assembly: TypeForwardedTo(typeof(Comparer))]
[assembly: TypeForwardedTo(typeof(Dictionary))]
[assembly: TypeForwardedTo(typeof(Dictionary.Enumerator))]
[assembly: TypeForwardedTo(typeof(Dictionary.KeyCollection.Enumerator))]
[assembly: TypeForwardedTo(typeof(Dictionary.ValueCollection.Enumerator))]
[assembly: TypeForwardedTo(typeof(List.Enumerator))]
[assembly: TypeForwardedTo(typeof(Queue.Enumerator))]
[assembly: TypeForwardedTo(typeof(Stack.Enumerator))]
[assembly: TypeForwardedTo(typeof(EqualityComparer))]
[assembly: TypeForwardedTo(typeof(Dictionary.KeyCollection))]
[assembly: TypeForwardedTo(typeof(List))]
[assembly: TypeForwardedTo(typeof(Queue))]
[assembly: TypeForwardedTo(typeof(Stack))]
[assembly: TypeForwardedTo(typeof(StructuralComparisons))]
[assembly: TypeForwardedTo(typeof(Dictionary.ValueCollection))]
// System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[assembly: TypeForwardedTo(typeof(SortedSet<>.ElementCount))]
[assembly: TypeForwardedTo(typeof(LinkedList<>.Enumerator))]
[assembly: TypeForwardedTo(typeof(SortedDictionary<, >.Enumerator))]
[assembly: TypeForwardedTo(typeof(SortedDictionary<, >.KeyCollection.Enumerator))]
[assembly: TypeForwardedTo(typeof(SortedDictionary<, >.ValueCollection.Enumerator))]
[assembly: TypeForwardedTo(typeof(SortedSet<>.Enumerator))]
[assembly: TypeForwardedTo(typeof(SortedDictionary<, >.KeyCollection))]
[assembly: TypeForwardedTo(typeof(SortedDictionary<, >.KeyValuePairComparer))]
[assembly: TypeForwardedTo(typeof(LinkedListNode<>))]
[assembly: TypeForwardedTo(typeof(LinkedList<>))]
[assembly: TypeForwardedTo(typeof(SortedSet<>.Node))]
[assembly: TypeForwardedTo(typeof(SortedDictionary<, >))]
[assembly: TypeForwardedTo(typeof(SortedList<, >))]
[assembly: TypeForwardedTo(typeof(SortedSet<>))]
[assembly: TypeForwardedTo(typeof(SortedSet<>.TreeSubSet))]
[assembly: TypeForwardedTo(typeof(SortedDictionary<, >.ValueCollection))]
// System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
[assembly: TypeForwardedTo(typeof(HashSet<>.ElementCount))]
[assembly: TypeForwardedTo(typeof(HashSet<>.Enumerator))]
[assembly: TypeForwardedTo(typeof(HashSet<>))]
[assembly: TypeForwardedTo(typeof(HashSet<>.Slot))]
