using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.Playables;

namespace Cinemachine
{
	// Token: 0x02000050 RID: 80
	[DocumentationSorting(DocumentationSortingAttribute.Level.UserRef)]
	[SaveDuringPlay]
	[HelpURL("https://docs.unity3d.com/Packages/com.unity.cinemachine@2.9/api/Cinemachine.CinemachineTriggerAction.html")]
	public class CinemachineTriggerAction : MonoBehaviour
	{
		// Token: 0x06000367 RID: 871 RVA: 0x0001542C File Offset: 0x0001362C
		private bool Filter(GameObject other)
		{
			return base.enabled && (1 << other.layer & this.m_LayerMask) != 0 && (this.m_WithTag.Length == 0 || other.CompareTag(this.m_WithTag)) && (this.m_WithoutTag.Length == 0 || !other.CompareTag(this.m_WithoutTag));
		}

		// Token: 0x06000368 RID: 872 RVA: 0x0001549C File Offset: 0x0001369C
		private void InternalDoTriggerEnter(GameObject other)
		{
			if (!this.Filter(other))
			{
				return;
			}
			this.m_SkipFirst--;
			if (this.m_SkipFirst > -1)
			{
				return;
			}
			if (!this.m_Repeating && this.m_SkipFirst != -1)
			{
				return;
			}
			this.m_ActiveTriggerObjects.Add(other);
			this.m_OnObjectEnter.Invoke();
		}

		// Token: 0x06000369 RID: 873 RVA: 0x000154F5 File Offset: 0x000136F5
		private void InternalDoTriggerExit(GameObject other)
		{
			if (!this.m_ActiveTriggerObjects.Contains(other))
			{
				return;
			}
			this.m_ActiveTriggerObjects.Remove(other);
			if (base.enabled)
			{
				this.m_OnObjectExit.Invoke();
			}
		}

		// Token: 0x0600036A RID: 874 RVA: 0x00015526 File Offset: 0x00013726
		private void OnTriggerEnter(Collider other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		// Token: 0x0600036B RID: 875 RVA: 0x00015534 File Offset: 0x00013734
		private void OnTriggerExit(Collider other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		// Token: 0x0600036C RID: 876 RVA: 0x00015542 File Offset: 0x00013742
		private void OnCollisionEnter(Collision other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		// Token: 0x0600036D RID: 877 RVA: 0x00015550 File Offset: 0x00013750
		private void OnCollisionExit(Collision other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		// Token: 0x0600036E RID: 878 RVA: 0x0001555E File Offset: 0x0001375E
		private void OnTriggerEnter2D(Collider2D other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		// Token: 0x0600036F RID: 879 RVA: 0x0001556C File Offset: 0x0001376C
		private void OnTriggerExit2D(Collider2D other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		// Token: 0x06000370 RID: 880 RVA: 0x0001557A File Offset: 0x0001377A
		private void OnCollisionEnter2D(Collision2D other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		// Token: 0x06000371 RID: 881 RVA: 0x00015588 File Offset: 0x00013788
		private void OnCollisionExit2D(Collision2D other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		// Token: 0x06000372 RID: 882 RVA: 0x00015596 File Offset: 0x00013796
		private void OnEnable()
		{
		}

		// Token: 0x04000242 RID: 578
		[Header("Trigger Object Filter")]
		[Tooltip("Only triggers generated by objects on these layers will be considered")]
		public LayerMask m_LayerMask = 1;

		// Token: 0x04000243 RID: 579
		[TagField]
		[Tooltip("If set, only triggers generated by objects with this tag will be considered")]
		public string m_WithTag = string.Empty;

		// Token: 0x04000244 RID: 580
		[TagField]
		[Tooltip("Triggers generated by objects with this tag will be ignored")]
		public string m_WithoutTag = string.Empty;

		// Token: 0x04000245 RID: 581
		[NoSaveDuringPlay]
		[Tooltip("Skip this many trigger entries before taking action")]
		public int m_SkipFirst;

		// Token: 0x04000246 RID: 582
		[Tooltip("Repeat the action for all subsequent trigger entries")]
		public bool m_Repeating = true;

		// Token: 0x04000247 RID: 583
		public CinemachineTriggerAction.ActionSettings m_OnObjectEnter = new CinemachineTriggerAction.ActionSettings(CinemachineTriggerAction.ActionSettings.Mode.Custom);

		// Token: 0x04000248 RID: 584
		public CinemachineTriggerAction.ActionSettings m_OnObjectExit = new CinemachineTriggerAction.ActionSettings(CinemachineTriggerAction.ActionSettings.Mode.Custom);

		// Token: 0x04000249 RID: 585
		private HashSet<GameObject> m_ActiveTriggerObjects = new HashSet<GameObject>();

		// Token: 0x020000C3 RID: 195
		[Serializable]
		public struct ActionSettings
		{
			// Token: 0x06000484 RID: 1156 RVA: 0x0001A03A File Offset: 0x0001823A
			public ActionSettings(CinemachineTriggerAction.ActionSettings.Mode action)
			{
				this.m_Action = action;
				this.m_Target = null;
				this.m_BoostAmount = 0;
				this.m_StartTime = 0f;
				this.m_Mode = CinemachineTriggerAction.ActionSettings.TimeMode.FromStart;
				this.m_Event = new CinemachineTriggerAction.ActionSettings.TriggerEvent();
			}

			// Token: 0x06000485 RID: 1157 RVA: 0x0001A070 File Offset: 0x00018270
			public void Invoke()
			{
				UnityEngine.Object target = this.m_Target;
				if (target != null)
				{
					GameObject gameObject = target as GameObject;
					Behaviour behaviour = target as Behaviour;
					if (behaviour != null)
					{
						gameObject = behaviour.gameObject;
					}
					switch (this.m_Action)
					{
					case CinemachineTriggerAction.ActionSettings.Mode.PriorityBoost:
					{
						CinemachineVirtualCameraBase component = gameObject.GetComponent<CinemachineVirtualCameraBase>();
						if (component != null)
						{
							component.Priority += this.m_BoostAmount;
							component.MoveToTopOfPrioritySubqueue();
						}
						break;
					}
					case CinemachineTriggerAction.ActionSettings.Mode.Activate:
						if (gameObject != null)
						{
							gameObject.SetActive(true);
							CinemachineVirtualCameraBase component2 = gameObject.GetComponent<CinemachineVirtualCameraBase>();
							if (component2 != null)
							{
								component2.MoveToTopOfPrioritySubqueue();
							}
						}
						break;
					case CinemachineTriggerAction.ActionSettings.Mode.Deactivate:
						if (gameObject != null)
						{
							gameObject.SetActive(false);
						}
						break;
					case CinemachineTriggerAction.ActionSettings.Mode.Enable:
						if (behaviour != null)
						{
							behaviour.enabled = true;
						}
						break;
					case CinemachineTriggerAction.ActionSettings.Mode.Disable:
						if (behaviour != null)
						{
							behaviour.enabled = false;
						}
						break;
					case CinemachineTriggerAction.ActionSettings.Mode.Play:
					{
						PlayableDirector component3 = gameObject.GetComponent<PlayableDirector>();
						if (component3 != null)
						{
							double num = 0.0;
							double duration = component3.duration;
							double time = component3.time;
							switch (this.m_Mode)
							{
							default:
								num += (double)this.m_StartTime;
								break;
							case CinemachineTriggerAction.ActionSettings.TimeMode.FromEnd:
								num = duration - (double)this.m_StartTime;
								break;
							case CinemachineTriggerAction.ActionSettings.TimeMode.BeforeNow:
								num = time - (double)this.m_StartTime;
								break;
							case CinemachineTriggerAction.ActionSettings.TimeMode.AfterNow:
								num = time + (double)this.m_StartTime;
								break;
							}
							component3.time = num;
							component3.Play();
						}
						else
						{
							Animation component4 = gameObject.GetComponent<Animation>();
							if (component4 != null)
							{
								component4.Play();
							}
						}
						break;
					}
					case CinemachineTriggerAction.ActionSettings.Mode.Stop:
					{
						PlayableDirector component5 = gameObject.GetComponent<PlayableDirector>();
						if (component5 != null)
						{
							component5.Stop();
						}
						else
						{
							Animation component6 = gameObject.GetComponent<Animation>();
							if (component6 != null)
							{
								component6.Stop();
							}
						}
						break;
					}
					}
				}
				this.m_Event.Invoke();
			}

			// Token: 0x040003D8 RID: 984
			[Tooltip("What action to take")]
			public CinemachineTriggerAction.ActionSettings.Mode m_Action;

			// Token: 0x040003D9 RID: 985
			[Tooltip("The target object on which to operate.  If null, then the current behaviour/GameObject will be used")]
			public UnityEngine.Object m_Target;

			// Token: 0x040003DA RID: 986
			[Tooltip("If PriorityBoost, this amount will be added to the virtual camera's priority")]
			public int m_BoostAmount;

			// Token: 0x040003DB RID: 987
			[Tooltip("If playing a timeline, start at this time")]
			public float m_StartTime;

			// Token: 0x040003DC RID: 988
			[Tooltip("How to interpret the start time")]
			public CinemachineTriggerAction.ActionSettings.TimeMode m_Mode;

			// Token: 0x040003DD RID: 989
			[Tooltip("This event will be invoked")]
			public CinemachineTriggerAction.ActionSettings.TriggerEvent m_Event;

			// Token: 0x020000F1 RID: 241
			public enum Mode
			{
				// Token: 0x040004AC RID: 1196
				Custom,
				// Token: 0x040004AD RID: 1197
				PriorityBoost,
				// Token: 0x040004AE RID: 1198
				Activate,
				// Token: 0x040004AF RID: 1199
				Deactivate,
				// Token: 0x040004B0 RID: 1200
				Enable,
				// Token: 0x040004B1 RID: 1201
				Disable,
				// Token: 0x040004B2 RID: 1202
				Play,
				// Token: 0x040004B3 RID: 1203
				Stop
			}

			// Token: 0x020000F2 RID: 242
			[Serializable]
			public class TriggerEvent : UnityEvent
			{
			}

			// Token: 0x020000F3 RID: 243
			public enum TimeMode
			{
				// Token: 0x040004B5 RID: 1205
				FromStart,
				// Token: 0x040004B6 RID: 1206
				FromEnd,
				// Token: 0x040004B7 RID: 1207
				BeforeNow,
				// Token: 0x040004B8 RID: 1208
				AfterNow
			}
		}
	}
}
